/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParamRespModel {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "query")]
    pub query: f32,
}

impl ParamRespModel {
    pub fn new(path: String, query: f32) -> ParamRespModel {
        ParamRespModel {
            path,
            query,
        }
    }
}


