/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UnionModel {
    #[serde(rename = "data")]
    pub data: Box<crate::models::Data>,
}

impl UnionModel {
    pub fn new(data: crate::models::Data) -> UnionModel {
        UnionModel {
            data: Box::new(data),
        }
    }
}


